### ISSUE TITLE
[Suggestion] Split database to new repository

### ISSUE THREAD

**Issue by phillc73** [sboulema/Hops#1]
I was wondering if it could make sense to split the actual hops database out to a new repository of its own. Then associated repositories could focus on different aspects of using the data.

For example, this repository develops a nice web based view. [Another repository](https://github.com/stuartraetaylor/hops-json) presents a json view of the data.

I think it could also make it somewhat easier to contribute to the database if it was held separately. Currently I'm aware of some hops varieties which are not yet in the database, e.g. [African Queen](https://learn.kegerator.com/african-queen-hops/) (unless I missed it), and I would like to contribute updates. A separation of data and presentation might make this easier.

**Comment by sboulema** [comment]
Delighted to see someone besides me having interest in this repo!
Thank you for the pull request.

And your suggestion absolutely makes sense, so I have splitted the db to a new repo: https://github.com/sboulema/BrewDB

**Comment by phillc73** [comment]
Great! Yes, I've been looking for a good database with hops, yeast and malts that I can query programmatically. This is the best one I've found so far. Happy to contribute.
